#!/bin/sh

cd
sudo apt-get install build-essential debhelper git pandoc shunit2 -y
git clone https://github.com/mkropat/jumpapp.git
cd jumpapp
make deb
sudo dpkg -i jumpapp*all.deb
# if there were missing dependencies
sudo apt-get install -f -y
cd
rm -rf jumpapp
