#!/bin/bash

cd

# Install Neovim
sudo apt install curl git cmake gettext -y

## Install latest npm
sudo apt purge npm
curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh
sudo -E bash nodesource_setup.sh
sudo apt-get install -y nodejs

# git clone https://github.com/neovim/neovim.git
# Git from GitHub maight be blocked by GFW
wget https://codeload.github.com/neovim/neovim/zip/refs/heads/master
unzip master
cd neovim-master
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

# Install LazyVim
mv ~/.config/nvim ~/.config/nvim.bak
mv ~/.local/share/nvim ~/.local/share/nvim.bak
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git

cd 
rm nodesource_setup.sh
rm -rf neovim-master
rm master

nvim
