#!/bin/bash

# Install Neovim
sudo apt update
sudo apt install curl wget unzip git cmake gettext npm xclip -y

mkdir ~/install-neovim-temp

cd ~/install-neovim-temp
wget https://codeload.github.com/neovim/neovim/zip/refs/heads/master
unzip master
cd neovim-master

make CMAKE_BUILD_TYPE=RelWithDebInfo -j$(nproc)
sudo make install

# Install LazyVim
cd ~/install-neovim-temp
mv ~/.config/nvim ~/.config/nvim.bak
mv ~/.local/share/nvim ~/.local/share/nvim.bak
wget https://codeload.github.com/LazyVim/starter/zip/refs/heads/main
unzip main
mkdir ~/.config/
mkdir ~/.config/nvim/
mv starter-main/* ~/.config/nvim/

rm -rf ~/.config/nvim/.git

# Uncomment this if you wanna set H and T as <Home> and <End>
cd ~/install-neovim-temp
wget --retry-on-host-error https://install-neovim.github.io/keymap --tries=0
sh keymap

cd ~
sudo rm ~/install-neovim-temp

nvim
