#!/bin/sh

sudo apt-get install git libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev libpython3-all-dev make
cd
git clone --recursive https://github.com/vysheng/tg.git && cd tg
./configure
make
