#!/bin/bash

# Install Neovim
pkg update
pkg install unzip git wget make cmake gettext nodejs binutils tsu -y

# git clone https://github.com/neovim/neovim.git
# Git from GitHub maight be blocked by GFW
wget https://codeload.github.com/neovim/neovim/zip/refs/heads/master
unzip master
cd neovim-master
make CMAKE_BUILD_TYPE=RelWithDebInfo -j$(nproc)
make install

# Install LazyVim
mv ~/.config/nvim ~/.config/nvim.bak
mv ~/.local/share/nvim ~/.local/share/nvim.bak
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git

cd 
rm -rf neovim-master
rm master
nvim
